url:
  bsd11: "https://mfsbsd.vx.sk/files/iso/11/amd64/mfsbsd-11.1-RELEASE-amd64.iso"
  bsd12: "https://mfsbsd.vx.sk/files/iso/12/amd64/mfsbsd-12.1-RELEASE-amd64.iso"
  debian_9: "http://ftp.debian.org/debian/dists/stretch/main/installer-amd64/current/images/netboot/netboot.tar.gz"
  debian_10: "http://ftp.debian.org/debian/dists/buster/main/installer-amd64/current/images/netboot/netboot.tar.gz"
  debian_11: "http://ftp.debian.org/debian/dists/bullseye/main/installer-amd64/current/images/netboot/netboot.tar.gz"
  centos_7_kernel: "http://mirror.mirohost.net/centos/7/os/x86_64/isolinux/vmlinuz"
  centos_7_initrd: "http://mirror.mirohost.net/centos/7/os/x86_64/isolinux/initrd.img"
  ubuntu_xenial: "http://archive.ubuntu.com/ubuntu/dists/xenial/main/installer-amd64/current/images/netboot/netboot.tar.gz"
  ubuntu_focal: "http://archive.ubuntu.com/ubuntu/dists/focal/main/installer-amd64/current/legacy-images/netboot/netboot.tar.gz"
  ubuntu_xenial_live: "https://releases.ubuntu.com/16.04.7/ubuntu-16.04.7-desktop-amd64.iso"
use_local_dhcp: "yes"
syslinux_url: "https://www.kernel.org/pub/linux/utils/boot/syslinux/4.xx/syslinux-4.02.tar.gz"
pxe_title_menu: "Boot Server"
address: "192.168.0.201"
local_network: "192.168.0.0/24"
tftp_root_dir: "/srv/tftp"
mount_dir: "mnt"
dir:
  debian_dir: "debian"
  debian_dir_version:
    - "9"
    - "10"
    - "11"
  centos_dir: "centos"
  centos_dir_version: "7"
  ubuntu_dir: "ubuntu"
  ubuntu_dir_version:
    - "16.04"
    - "20.04"
  ubuntu_live_dir: "live"
  bsd_dir: "freebsd"
  bsd_dir_version: 
    - "11"
    - "12"
dhcp:
  dns1: "8.8.8.8"
  dns2: "8.8.4.4"
  subnet: "192.168.0.0"
  netmask: "255.255.255.0"
  range: "192.168.0.50 192.168.0.55"
  gw: "192.168.0.1"
  filename: "pxelinux.0"
  next_server: "192.168.0.201"
  interface: "eth1"